name: CI CMake

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: get
        uses: actions/checkout@v4

      - name: configure
        run: cmake -S tests -B tests/build -DBUILD_TESTS=ON
        working-directory: .

      - name: build
        run: cmake --build tests/build --config Debug
        working-directory: .

      - name: run tests
        run: ./tests/build/tests
        working-directory: .

      - name: Generate coverage
        working-directory: .
        run: |
          pip install gcovr
          gcovr \
            --root . \
            --exclude 'tests/.*' \
            --lcov \
            -o coverage.info \
            tests/build

      - name: upload to coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.info
